apiVersion: v1
kind: Namespace
metadata:
  name: nodejsapp
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tahs-nodejsapp-deployment
  namespace: nodejsapp
  labels:
    app: tahs-nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tahs-nodejsapp
  template:
    metadata:
      labels:
        app: tahs-nodejsapp 
    spec:
      containers:
      - name: nodeserver
        image: tahs01/nodejs_app:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: tahs-nodeapp-service
  namespace: nodejsapp
spec:
  selector:
    app: tahs-nodejsapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
